### ISSUE TITLE
ApolloTest make 报错

### ISSUE THREAD

**Issue by heilaoda** [shiwendai/ApolloCppSDK#1]
环境：Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) )  
           CentOS Linux release 7.4.1708 (Core)

报错内容如下：
../../3rdparty/aliyun/3thparty/lib_release/lnx_x64/libcurl.so: undefined reference to `UI_method_set_writer@OPENSSL_1.0.0'collect2: error: ld returned 1 exit status
make: *** [build/lib/ApolloTest] Error 1

**Comment by shiwendai** [comment]
你是编译失败，还是运行失败
